language: python
dist: xenial
sudo: false

python:
  - "3.6"
  - "3.7"
  - 3.8-dev

install:
  - pip install -r requirements_dev.txt
  - pip install -e .

script:
  - pytest tests/
  - black --check .
